@UsersManagement_HostAddress = http://localhost:5062/api

### Get all users
GET {{UsersManagement_HostAddress}}/Users
Accept: application/json

### Get a user by ID
GET {{UsersManagement_HostAddress}}/Users/1
Accept: application/json

### Create a new user
POST {{UsersManagement_HostAddress}}/Users
Content-Type: application/json
{
  "name": "John Doe",
  "cpf": "98765432100",
  "celphone": "54991892378",
  "email": "johndoe@gmail.com"
}
Accept: application/json

### Update an existing user
PUT {{UsersManagement_HostAddress}}/Users/1
Content-Type: application/json
{
  "name": "Jane Doe",
  "cpf": "12345678900",
  "celphone": "54991892379",
  "email": "
}
Accept: application/json

### Delete a user
DELETE {{UsersManagement_HostAddress}}/Users/1
Accept: application/json

###
